# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Markdown
  - trigger: ":a"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ":b"
    replace: "**$|$**"
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ":code"
    replace: |
      ```
      $|$
      ```
  
  - trigger: ":today"
    replace: "{{mytoday}}"
    vars:
      - name: mytoday
        type: date
        params:
          format: "%e %b %Y"

  - trigger: ":dailies"
    replace: "{{mytoday}}"
    vars:
      - name: mytoday
        type: date
        params:
          format: "# %A, %e %B %Y"

  # Time
  - trigger: ":now"
    replace: "{{mytime}}"
    vars:
      - name: mytime 
        type: date
        params:
          format: "%H:%M"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
          
  # Database connection string
  - trigger: ":dbds"
    replace: "dbdriver://username:password@host:port/dbname?param1=true&param2=false"

  - trigger: ":progress"
    replace: "<progress value=\"{{clipboard}}\" max=\"100\">{{clipboard}}%</progress>"
    vars:
      - name: "clipboard"
        type: "clipboard"

